[ejbca-test1-1] add steps to action

diff --git a/.github/workflows/first-test.yml b/.github/workflows/first-test.yml
--- a/.github/workflows/first-test.yml
+++ b/.github/workflows/first-test.yml
@@ -46,3 +46,12 @@ jobs:
             echo "| Total | Passed | Failed | Skipped |" >> $GITHUB_STEP_SUMMARY
             echo "|-------|--------|--------|---------|" >> $GITHUB_STEP_SUMMARY
             echo "| $total | $passed | $failed | $skipped |" >> $GITHUB_STEP_SUMMARY
+
+            # Export the failed count for use in subsequent steps
+            echo "FAILED_TESTS=$failed" >> $GITHUB_ENV            
+
+      - name: Fail if too many tests failed
+        if: env.FAILED_TESTS > 1
+        run: |
+            echo "Build failed because more than 1 test failed."
+            exit 1  
