[ejbca/test1-1] add action to performance test

diff --git a/.github/workflows/performance-test.yml b/.github/workflows/performance-test.yml
--- a/.github/workflows/performance-test.yml
+++ b/.github/workflows/performance-test.yml
@@ -82,19 +82,14 @@ jobs:
           -Jca_name=${{ inputs.ca_name }} \
           -Jsubject_dn=${{ inputs.subject_dn }} \
           -e -o report-${RUN_ID} 
-          exit_code=$?
- 
-          # If the test failed (exit code not 0), fail the workflow
-          if [ $exit_code -ne 0 ]; then
-            echo "JMeter test failed with exit code $exit_code"
-            exit $exit_code
-          fi
+          exit_code=$? 
+          echo "JMETER_RETURNVALUE=$exit_code" >> $GITHUB_ENV
 
           # Check if there are any failures in the result file (result.jtl)
           failures=$(grep -c 'failure="true"' test-results-${RUN_ID}.jtl)          
           if [ $failures -gt 0 ]; then
             echo "JMeter test failed with $failures failures."
-            exit 1
+            echo "JMETER_RETURNVALUE=1" >> $GITHUB_ENV
           fi          
         env:
           RUN_ID: ${{ env.RUN_ID }}
@@ -109,7 +104,14 @@ jobs:
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: report-${{ env.RUN_ID }}          
+          publish_dir: report-${{ env.RUN_ID }}
+      
+      - name: Run final exit check
+        run: |
+          if [ "$JMETER_RETURNVALUE" -ne 0 ]; then
+            echo "Job failed due to JMeter test failures."
+            exit 1          
+          fi        
 
 #      - name: Checkout gh-pages branch
 #        uses: actions/checkout@v3
